package com.instrumentwebsite.musicalinstruments.util;

public class EmailTemplate {

    public static String getVerificationTemplate(String username, String verifyLink) {
        return "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                + "<title>Verify Your Email - HarmonyHub</title>"
                + "</head>"
                + "<body style='font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background-color: #f4f4f4;'>"
                + "<div style='max-width: 600px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1);'>"
                + "<div style='text-align: center; margin-bottom: 20px;'>"
                + "<h2 style='color: #333;'>Verify Your Email Address</h2>"
                + "</div>"
                + "<div style='padding: 20px;'>"
                + "<p>Hello " + username + ",</p>"
                + "<p>Thank you for registering with HarmonyHub! Please verify your email address by clicking the button below:</p>"
                + "<p style='text-align: center;'>"
                + "<a href='" + verifyLink + "' style='display: inline-block; padding: 10px 20px; "
                + "background-color: #F28123; color: #ffffff; text-decoration: none; "
                + "border-radius: 5px; margin: 20px 0;' onclick='return confirm(\"Are you sure you want to verify this email address?\");'>Verify Email</a>"
                + "</p>"
                + "<p><strong>Note:</strong> By verifying your email, you confirm that this is your email address and agree to receive important notifications from HarmonyHub.</p>"
                + "<p>This link will expire in 5 minutes.</p>"
                + "<p>If you didn't create an account, you can safely ignore this email.</p>"
                + "<hr style='border: 1px solid #eee; margin: 20px 0;'>"
                + "<div style='text-align: center; color: #666; font-size: 12px;'>"
                + "<p>© 2024 HarmonyHub. All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String getPasswordResetTemplate(String resetLink) {
        return "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                + "<title>Reset Password - HarmonyHub</title>"
                + "</head>"
                + "<body style='font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background-color: #f4f4f4;'>"
                + "<div style='max-width: 600px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1);'>"
                + "<div style='text-align: center; margin-bottom: 20px;'>"
                + "<h2 style='color: #333;'>Password Reset Request</h2>"
                + "</div>"
                + "<div style='padding: 20px;'>"
                + "<p>Hello,</p>"
                + "<p>We received a request to reset your password for your HarmonyHub account. "
                + "Click the link below to reset it:</p>"
                + "<p style='text-align: center;'>"
                + "<a href='" + resetLink + "' style='display: inline-block; padding: 10px 20px; "
                + "background-color: #F28123; color: #ffffff; text-decoration: none; "
                + "border-radius: 5px; margin: 20px 0;'>Reset Password</a>"
                + "</p>"
                + "<p>If you didn't request this, you can safely ignore this email.</p>"
                + "<p>This link will expire in 24 hours.</p>"
                + "<hr style='border: 1px solid #eee; margin: 20px 0;'>"
                + "<div style='text-align: center; color: #666; font-size: 12px;'>"
                + "<p>© 2024 HarmonyHub. All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String getWelcomeTemplate(String username) {
        return "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                + "<title>Welcome to HarmonyHub</title>"
                + "</head>"
                + "<body style='font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background-color: #f4f4f4;'>"
                + "<div style='max-width: 600px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1);'>"
                + "<div style='text-align: center; margin-bottom: 20px;'>"
                + "<h2 style='color: #333;'>Welcome to HarmonyHub!</h2>"
                + "</div>"
                + "<div style='padding: 20px;'>"
                + "<p>Hello " + username + ",</p>"
                + "<p>Welcome to HarmonyHub - Your Ultimate Musical Instrument Store!</p>"
                + "<p>We're excited to have you join our community of music lovers. "
                + "Start exploring our collection of high-quality instruments today.</p>"
                + "<p style='text-align: center;'>"
                + "<a href='#' style='display: inline-block; padding: 10px 20px; "
                + "background-color: #F28123; color: #ffffff; text-decoration: none; "
                + "border-radius: 5px; margin: 20px 0;'>Start Shopping</a>"
                + "</p>"
                + "<hr style='border: 1px solid #eee; margin: 20px 0;'>"
                + "<div style='text-align: center; color: #666; font-size: 12px;'>"
                + "<p>© 2024 HarmonyHub. All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }
}